apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: gprc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.healthcheckPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.healthcheckPort }}
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.healthcheckPort }}    
            initialDelaySeconds: 30
          env:
            - name: SERVICE_NAME
              value: {{ include "charts.fullname" . }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: keyfactor-credentials
            mountPath: /credentials
          - name: keyfactor-config
            mountPath: /config
          {{- if .Values.keyfactor.preProvisioningCertSecretName }}
          - name: keyfactor-pre-provisioning-certs
            mountPath: /certs
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: keyfactor-credentials
        secret:
          secretName: {{ .Values.keyfactor.secretName }}
      - name: keyfactor-config
        configMap:
          name: keyfactor-config
      {{- if .Values.keyfactor.preProvisioningCertSecretName }}
      - name: keyfactor-pre-provisioning-certs
        secret:
          secretName: {{ .Values.keyfactor.preProvisioningCertSecretName }}
      {{- end }}
