apiVersion: v1
kind: ConfigMap
metadata:
  name: keyfactor-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
  {{- toYaml .Values.keyfactor | nindent 4}}
    gRPCPort: {{ .Values.service.port }}
    healthcheckPort: {{ .Values.service.healthcheckPort }}